name: video_tools
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  path_provider: ^2.1.5
  convert: ^3.1.2
  file_picker: ^10.3.7
  path: ^1.9.1
  shared_preferences: ^2.5.3
  window_manager: ^0.5.1
  desktop_drop: ^0.7.0
  cross_file: ^0.3.5+1
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: any
  isar_community_generator: ^3.3.0

flutter:
  uses-material-design: true
